### ISSUE TITLE
`assert len(edges) == 1` AssertionError in Class tree view

### ISSUE THREAD

**Issue by Wuestengecko** [DSD-DBS/capellambse-context-diagrams#81]
I get an error when generating a class tree view for one of the classes in the In-Flight Entertainment System demo model.

- capellambse v0.5.51
- capellambse_context_diagrams v0.2.31

```
$ ./capellambse/repl.py ife-demo
[...]
>>> model.by_uuid("8a3c3a57-1ff3-4d9e-845e-0e142c1ca7dc").tree_view.render("svg")
12:50:05.276 <capellambse_context_diagrams.collectors.tree_view> DEBUG: Ignoring non-class property: "<Property 'class' (8bec7dec-3987-4b7d-afbc-5aaa8d2efd64)>"
12:50:05.276 <capellambse_context_diagrams.collectors.tree_view> DEBUG: Ignoring non-class property: "<Property 'name' (2b0362f6-7d62-4804-a024-bedb01a54407)>"
12:50:05.277 <capellambse_context_diagrams.collectors.tree_view> DEBUG: Ignoring non-class property: "<Property 'firstName' (bdf90720-78fc-42f6-a5bf-be969c862c6c)>"
12:50:05.278 <capellambse_context_diagrams.collectors.tree_view> DEBUG: Ignoring non-class property: "<Property 'class' (8bec7dec-3987-4b7d-afbc-5aaa8d2efd64)>"
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/wuestengecko/Wörk/devspace/capellambse-context-diagrams/capellambse_context_diagrams/context.py", line 341, in render
    return super().render(fmt, **rparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wuestengecko/Wörk/devspace/capellambse/capellambse/model/diagram.py", line 283, in render
    render = self.__render_fresh(params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wuestengecko/Wörk/devspace/capellambse/capellambse/model/diagram.py", line 441, in __render_fresh
    raise self._error
  File "/home/wuestengecko/Wörk/devspace/capellambse/capellambse/model/diagram.py", line 435, in __render_fresh
    self._render = self._create_diagram(params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wuestengecko/Wörk/devspace/capellambse-context-diagrams/capellambse_context_diagrams/context.py", line 428, in _create_diagram
    data, legend = tree_view.collector(self, params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wuestengecko/Wörk/devspace/capellambse-context-diagrams/capellambse_context_diagrams/collectors/tree_view.py", line 137, in collector
    processor.process_class(cls, params)
  File "/home/wuestengecko/Wörk/devspace/capellambse-context-diagrams/capellambse_context_diagrams/collectors/tree_view.py", line 57, in process_class
    assert len(edges) == 1
AssertionError
```

**Comment by ewuerger** [comment]
This means that there is no association in your model that can be associated with the property at hand.

**Comment by Wuestengecko** [comment]
> that can be associated with the property at hand

What do you mean with that? I want to see a diagram about a Class, not an individual property.

And what does it mean for me? Do I have to catch the exception and display some kind of "nothing to see here" message? If that's the case, please change the exception type. `assert` statements are meant to verify that the internal invariants you rely on are upheld, to guard against logic errors - they're not meant for input validation. You're basically saying that "if we don't find exactly one matching edge, there's a bug in our Python code".

By the way, I forgot to mention: This happens for three different classes in that model (I only mentioned the one I first discovered in the OP):

```
<Class 'Cabin' (8a3c3a57-1ff3-4d9e-845e-0e142c1ca7dc)>
<Class 'Passenger' (69bc8e28-37ec-4b2b-b47d-0cfb9ea8e645)>
<Class 'Aircraft' (67bd0af1-6242-4dec-aeef-3f54a7d8ba47)>
```

**Comment by ewuerger** [comment]
Todo: Improve Error message and give a hint on how to change the model.
